---
title: "Beeswarm plot with error, median, and p value"
author: "Emily Hatch"
date: "2023-08-20"
output: output: 
  html_document:
    keep_md: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(cache = TRUE, echo = TRUE, warning = FALSE, message = FALSE, error = FALSE, fig_width = 4, fig_height = 6, fig_retina = TRUE, dev = c("png", "pdf"))
```

#### Install dependencies

```{r dependencies}
library(tidyverse)
library(readxl)
library(ggbeeswarm)
library(ggpubr)
library(rstatix)
```

#### Calculate p-values in a new data frame and specify graph coordinates

```{r p_values}
df_p <- Asymp_model %>%
  ungroup() %>% # necessary if there are any groupings for model to work
  t_test(Est_fold_change ~ MN_PN) %>% # mutliple tests possible - look at rstatix library
  add_significance() %>% # gives you the summary (ns, *, etc.) in a column.
  add_xy_position(x = "MN_PN") # tells where to graph the p-value in the x, y. Data added in a column.

# Clean
df_p <- df %>%
  ungroup() %>% 
  t_test(y ~ x) %>% 
  add_significance() %>% 
  add_xy_position(x = "MN_PN")
```

#### Plot data
```{r beeswarm plot}
plot_df <- df %>%
  ggplot(aes(y = y, x = x, color = group)) +
  stat_summary(fun.data=mean_se, fun.args = list(mult=2), # adds error bars, can use any function on the data. mean_se + mult = 2 gives you 95% CI of mean. Uses grouping specified in color.
               geom="errorbar", color="black", width=0.2) + # geom = "error bar" says, this is an geom_errorbar style plot.
  stat_summary(fun.y=median, geom="point", shape = 22, size = 2, color="black", fill = "red") + # adds the median point. Shape 22 is an open square.
  geom_beeswarm(show.legend = FALSE) + # add beeswarm plot underneath the other ones.
  stat_pvalue_manual(df_p, label = "p.signif") + # add stats calculated above in places specifed above. Can report p values or p.signif, which is the ns etc. Requires gpubrr. 
  scale_color_brewer(palette = "Dark2") +
  coord_cartesian(ylim = c(0, 4)) + # use instead of scale_x or scale_y. It calculates based on all the values and then crops the graph. 
  labs(x = "", y = "y") +
  theme(text = element_text(size = 11))

print(plot_df)
#ggsave("final_images/F1F_live_v_fixed_rupturefrequency.tif", height = 4, width = 2, units = "in")
```
#### Get table of summary statistics (if desired)
```{r summary_stats easy table}
df %>%
  group_by(ColName) %>%
  get_summary_stats(y.Col.name, type = "median_iqr") # more available in rstatix package. More info available in "adding summary statistics to graphs.R"
```
#### Add summary statistics to table (the long way)
```{r add statistics by mutate}

df_stats <- dfl %>%
    group_by(group) %>%
    mutate(
      median = median(y, na.rm = TRUE),
      std_err = sd(y, na.rm = TRUE) / sqrt(n()))

```
## Clean version of code - mean cI

```{r beeswarm plot clean}
plot_df <- df %>%
  ggplot(aes(y = y, x = x, color = group)) +
  stat_summary(fun.data=mean_se, fun.args = list(mult=2),
               geom="errorbar", color="black", width=0.2) + 
  stat_summary(fun.y=median, geom="point", shape = 22, size = 2, color="black", fill = "red") + 
  geom_beeswarm(show.legend = FALSE) + 
  stat_pvalue_manual(df_p, label = "p.signif") + 
  scale_color_brewer(palette = "Dark2") +
  coord_cartesian(ylim = c(0, 4)) + 
  labs(x = "", y = "y") +
  theme(text = element_text(size = 11))

print(plot_df)
#ggsave("final_images/F1F_live_v_fixed_rupturefrequency.tif", height = 4, width = 2, units = "in")
```
#### Alternatives
1. Median CI in stat summary
2. Per group median/means
```{r Alternatives}
# Median CI function
quantile_cl <- function(y, q=0.5, conf.level = 0.95, na.rm=TRUE) {
  alpha <- 1 - conf.level
  if (na.rm) y <- y[!is.na(y)]
  n <- length(y)
  l <- qbinom(alpha/2, size=n, prob = q)
  u <- 1 + n - l
  ys <- sort.int(c(-Inf, y, Inf), partial = c(1 + l, 1 + u))
  data.frame(
    y = quantile(y, probs = q, na.rm=na.rm, type = 8),
    ymin = ys[1 + l],
    ymax = ys[1 + u]
  )
}

median_cl <- function(y, conf.level=0.95, na.rm=TRUE) quantile_cl(y, q=0.5, conf.level=conf.level, na.rm=na.rm)

# Use in stat_summary. Plotted using geom = plotranger
stat_summary(fun.data=median_cl, color="black", size= 0.2)

# Stat_summary with groupings
stat_summary(fun = median, geom = "point", aes(group = group, color = group))

```

